package com.vaidyo.vaidyo_backend.service;

import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.Base64;

@Service
public class LabReportService {

    private final GeminiService geminiService;

    public LabReportService(GeminiService geminiService) {
        this.geminiService = geminiService;
    }

    private static final String DISCLAIMER =
            "⚠️ DISCLAIMER: This summary is generated by an AI and is NOT a medical diagnosis. " +
                    "Please consult a qualified doctor to understand your lab results properly.";

    public String getDisclaimer() {
        return DISCLAIMER;
    }

    public String analyzeReport(MultipartFile file) throws IOException {
        String contentType = file.getContentType();

        if (contentType != null && contentType.equals("application/pdf")) {
            return "PDF lab reports are not supported yet. " +
                    "Please upload a photo (JPG or PNG) of your lab report.";
        }

        return analyzeImageWithGroq(file);
    }

    private String analyzeImageWithGroq(MultipartFile file) throws IOException {
        String base64Image = Base64.getEncoder()
                .encodeToString(file.getBytes());
        String mediaType = file.getContentType() != null
                ? file.getContentType() : "image/jpeg";

        String prompt = """
            You are a helpful medical assistant in a healthcare app called Vaidyo, \
            designed for patients in India including rural areas.

            The patient has uploaded an image of their lab report.

            Please:
            1. Read all the values visible in the lab report image
            2. Summarize the key findings in simple, plain English
            3. Highlight any values that are outside the normal range (HIGH or LOW)
            4. Explain what those abnormal values might mean in simple terms
            5. Give general advice on what the patient should do next

            Keep the language very simple — the patient may not have a medical background.

            IMPORTANT: End by reminding the patient that this is NOT a medical diagnosis \
            and they must consult a real doctor to understand their results properly.
            """;

        return geminiService.generateContentWithImage(base64Image, mediaType, prompt);
    }
}