package com.vaidyo.vaidyo_backend.controller;

import com.vaidyo.vaidyo_backend.dto.FoodRecommendationRequest;
import com.vaidyo.vaidyo_backend.dto.FoodRecommendationResponse;
import com.vaidyo.vaidyo_backend.service.GeminiService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/patient")
public class FoodRecommendationController {

    private final GeminiService geminiService;

    private static final String DISCLAIMER =
            "⚠️ DISCLAIMER: These dietary suggestions are generated by an AI and are NOT a substitute " +
                    "for professional medical or nutritional advice. Please consult a qualified doctor or " +
                    "dietitian before making significant changes to your diet.";

    public FoodRecommendationController(GeminiService geminiService) {
        this.geminiService = geminiService;
    }

    @PostMapping("/food-recommendation")
    public ResponseEntity<FoodRecommendationResponse> getFoodRecommendation(
            @RequestBody FoodRecommendationRequest request) {

        if (request.getCondition() == null || request.getCondition().trim().isEmpty()) {
            return ResponseEntity.badRequest().build();
        }

        String prompt = buildPrompt(request.getCondition());
        String aiResponse = geminiService.generateContent(prompt);

        FoodRecommendationResponse response = new FoodRecommendationResponse(aiResponse, DISCLAIMER);
        return ResponseEntity.ok(response);
    }

    private String buildPrompt(String condition) {
        return """
            You are a helpful dietary assistant in a healthcare app called Vaidyo, \
            designed for patients in India including rural areas.

            A patient has the following health condition or disease:
            "%s"

            Please provide:
            1. Foods they SHOULD eat — list 5-7 beneficial foods with a brief reason for each
            2. Foods they SHOULD AVOID — list 4-5 foods that may worsen their condition
            3. A simple Indian meal plan suggestion for one day (breakfast, lunch, dinner)
            4. Any general dietary tips specific to their condition

            Keep the response simple and practical for Indian households.
            Suggest commonly available Indian foods where possible.
            Avoid overly technical nutrition terms.

            IMPORTANT: End your response by reminding the patient that this is NOT professional \
            medical nutrition advice and they should consult a doctor or dietitian.
            """.formatted(condition);
    }
}