package com.vaidyo.vaidyo_backend.controller;

import com.vaidyo.vaidyo_backend.dto.SymptomCheckerRequest;
import com.vaidyo.vaidyo_backend.dto.SymptomCheckerResponse;
import com.vaidyo.vaidyo_backend.service.GeminiService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/patient")
public class SymptomCheckerController {

    private final GeminiService geminiService;

    private static final String DISCLAIMER =
            "⚠️ DISCLAIMER: This analysis is generated by an AI and is NOT a medical diagnosis. " +
                    "It is for informational purposes only. Please consult a qualified doctor for proper diagnosis and treatment.";

    public SymptomCheckerController(GeminiService geminiService) {
        this.geminiService = geminiService;
    }

    @PostMapping("/symptom-checker")
    public ResponseEntity<SymptomCheckerResponse> checkSymptoms(
            @RequestBody SymptomCheckerRequest request) {

        if (request.getSymptoms() == null || request.getSymptoms().trim().isEmpty()) {
            return ResponseEntity.badRequest().build();
        }

        String prompt = buildPrompt(request.getSymptoms());
        String geminiResponse = geminiService.generateContent(prompt);

        SymptomCheckerResponse response = new SymptomCheckerResponse(geminiResponse, DISCLAIMER);
        return ResponseEntity.ok(response);
    }

    private String buildPrompt(String symptoms) {
        return """
            You are a helpful medical assistant in a healthcare app called Vaidyo, \
            designed for patients in India including rural areas.

            A patient has described the following symptoms:
            "%s"

            Please provide:
            1. Possible conditions that may cause these symptoms (list 2-4 likely ones)
            2. General self-care advice for immediate relief
            3. A clear recommendation on whether they should see a doctor urgently, \
            soon, or can manage at home
            4. Any red flag symptoms they should watch for that require emergency care

            Keep the response clear and simple — the patient may not have a medical background.
            Use plain English. Avoid overly technical terms.

            IMPORTANT: End your response by reminding the patient that this is NOT a \
            medical diagnosis and they should consult a real doctor for proper treatment.
            """.formatted(symptoms);
    }
}